apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: 2ndcron
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: first
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from 2nd CronJob of OpenShift4.6
          restartPolicy: OnFailure
